version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tihouseworktest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1687d63apgjc2"
s3_prefix = "tihouseworktest"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "WebSocketTableName=\"chat_connections\""
