version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tihousework"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1687d63apgjc2"
s3_prefix = "tihousework"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
