AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TiHouseworkServer

  Sample SAM Template for TiHouseworkServer
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    CodeUri: TiHouseworkServer/
    Runtime: nodejs14.x
    Environment:
        Variables:
            USER_TABLE: user

Resources:

  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
          Name: email
          Type: String
      TableName: user
            
  LoginFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: app.login
      Events:
        Login:
          Type: Api 
          Properties:
            Path: /user/login
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable

  RegisterFunction:
      Type: AWS::Serverless::Function 
      Properties:
        Handler: app.register
        Events:
          Login:
            Type: Api 
            Properties:
              Path: /user/register
              Method: post
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref UserTable


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  API_endPoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  RegisterFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RegisterFunction.Arn
  RegisterFunctionRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RegisterFunctionRole.Arn
