AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TiHouseworkServer

  Sample SAM Template for TiHouseworkServer
  
Parameters:
  TableName:
    Type: String
    Default: 'simplechat_connections'
    Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'
    
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    Environment:
      Variables:
        USER_TABLE: user

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn
    
  # DynamoDB Tables
  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
          Name: email
          Type: String
      TableName: user
  
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "connectionId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "connectionId"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref TableName

  # API Functions   
  LoginFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/main/
      Handler: app.login
      Events:
        Login:
          Type: Api 
          Properties:
            Path: /user/login
            Method: post
            RestApiId : !Ref MyApi
            Auth:
              Authorizer: NONE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable

  RegisterFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: src/main/
        Handler: app.register 
        Events:
          Register:
            Type: Api 
            Properties:
              RestApiId : !Ref MyApi
              Path: /user/register
              Method: post
              Auth:
                Authorizer: NONE
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref UserTable

  HelloFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: src/main/
        Handler: app.hello
        Events:
          Hello:
            Type: Api 
            Properties:
              RestApiId : !Ref MyApi
              Path: /hello
              Method: get



  # Auth Functions  
  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/
      Handler: app.auth
      

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  APIEndPoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  RegisterFunction:
    Description: "Register Lambda Function ARN"
    Value: !GetAtt RegisterFunction.Arn
  RegisterFunctionRole:
    Description: "Implicit IAM Role created for Registerfunction"
    Value: !GetAtt RegisterFunctionRole.Arn
